### ISSUE TITLE
How to contribute tips

### ISSUE THREAD

**Issue by paulo-romano** [dirtycoder/pets#12]
@dirtycoder,

I think that is a good ideia, add some extra information about how to contribute to the project. What do you think about this change in the end of README file?

------------------------------------------------------------------------------------------------------

### How to contribute to the project

In order to make development and deploy to production simpler there's two settings module.
'dev' for development and 'prod' for production, both based on the 'base' settings.

Look in the settings modules for environment variables which need to be configured.

Install dependencies and requirements:

```console
#Pillow dependencies
sudo apt-get install python-dev python3.x-dev libjpeg8-dev

#PhantomJS, see the julionc tutorial at https://gist.github.com/julionc/7476620

pip install -r requirements.txt

```

**Comment by dirtycoder** [comment]
Maybe we should also add something about virtualenv, what do you think?

**Comment by paulo-romano** [comment]
You're right. 

And some other things about environment vars, just to make it more easy.

I will think in something and show it to you before a PR.

**Comment by paulo-romano** [comment]
@dirtycoder please, see the commit mentioned above.

**Comment by dirtycoder** [comment]
@paulo-romano can you submit it as a pull request?
