### ISSUE TITLE
Improve the UI

### ISSUE THREAD

**Issue by dirtycoder** [dirtycoder/pets#16]
The current version is really simplistic.
It could be a lot better.

**Comment by rohanthacker** [comment]
Hey @dirtycoder 
What kind of UI would you like to see this project have? Perhaps we could pool together a few links to reference sites that could be used as inspiration for this site?

**Comment by dirtycoder** [comment]
Hey @rohanthacker!

So I have something in mind already, there's a branch called `new-layout` where I started to work on it.
I believe I have something in my local repo that I need to push to the branch, I'll probably do it this weekend.

Then we talk again about it. :)

**Comment by dirtycoder** [comment]
The new home is shaping up like this:
![imagem da pagina 2016-07-10 as 11 43 27](https://cloud.githubusercontent.com/assets/1988429/16714264/a4030d98-4693-11e6-8204-665224329a53.png)

Scrolling down the page will apply a new style to the navbar:
![imagem da pagina 2016-07-10 as 11 43 42](https://cloud.githubusercontent.com/assets/1988429/16714263/a3ff4e42-4693-11e6-8570-990bc3dfe00f.png)
