### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by dirtycoder** [dirtycoder/pets#17]
Maybe a mobile app could even improve the usage rate of the application.

I believe we could use something like Xamarin or React Native?
But I don't know if it's really useful, as the store fee is kinda prohibitive for a nonprofit project. 

Ideally this will required some coordination with #18.

**Comment by cuducos** [comment]
React Native sounds useful. [That Hangouts about Phonegap](https://youtu.be/7QZgxq5QTnU) might be useful as well.

Anyway, whatever technology behind the mobile app, I think the first step is to design a kind of (RESTful?) API to feed the app, right? (I mean, if it isn't done already? Newbie here anyway…)

**Comment by dirtycoder** [comment]
Hey @cuducos, exactly.

I was thinking at the first step as adding just a read-only endpoint to list the pets.
With a full featured API if the mobile app become much popular I'm afraid that the U$ 5 droplet on DigitalOcean wont handle it.

But I might be wrong, I'm not very used to resource consumption of such a thing.
I was taking a look at Django REST Framework and it have a very useful feature, [throttling](http://www.django-rest-framework.org/api-guide/throttling/).

And to be honest I was just waiting for your interaction with the project so I can mention you on #18, as I saw you have some experience with it. :) haha

**Comment by cuducos** [comment]
Django REST Framework sounds pretty cool. I never used, but honestly I'm just wanting for some extra time to study and play around with it.

About infrastructure: if the platform gets popular (doesn't matter if via site or app) we'll have a bunch of users that might help with some donations to keep the things running.

If we have 1000 _heavy_ users, and each one of them donates R$ 0,10/month via [Unlock](http://unlock.fund), we will have roughly USD 30/month to pay for servers.

No one can actually donate R$ 0,10 there, but the ratio is what matters: from a 1000 users base, 1% donating R$ 10, or 2% donating R$ 5, does the trick.

In other news, probably my first hours coding for this project will be sweeping #18 away ; )

**Comment by dirtycoder** [comment]
Makes sense...

Hey that's great!
Let me know if you need some help.

**Comment by dirtycoder** [comment]
So I started working on the Android app, it'll probably take same time because of my lack of experience and free time, but sooner or later it'll be done. :)

**Comment by dirtycoder** [comment]
I'll close this, when (if?) this app is really done it'll take place here:
https://github.com/dirtycoder/pets-android
