### ISSUE TITLE
Simple API endpoint to query latest registered pets

### ISSUE THREAD

**Issue by dirtycoder** [dirtycoder/pets#18]
For now this could be very simple and read-only I believe.
But as I would like it to not be a problem for resource usage in case of usage abuse, I think we need something to control the rate of requests.

**Comment by rohanthacker** [comment]
Would setting a cache be an acceptable solution, in the use case that you mention?

As I believe the primary resource usage would be the database query, eliminating this to a reasonable invalidation period, would help in reducing resource usage? 

What do you think?



Reference : https://www.dabapps.com/blog/api-performance-profiling-django-rest-framework/

**Comment by dirtycoder** [comment]
@rohanthacker sure!
I was thinking about this too.
There's a few "discussion" about this too in #17.

But I'd like to leave the cache layer modification to be made before everything, if and when we really come to need it.

Right now what I would really like is to add an action in the admin to share the selected pets in the Facebook page. The sharing stuff is already a Django command.
Would you like to do/discuss this? 
(I'll create a new issue)
