### ISSUE TITLE
Selenium tests randomly timeout in Travis

### ISSUE THREAD

**Issue by dirtycoder** [dirtycoder/pets#21]
Seems related:
https://github.com/travis-ci/travis-ci/issues/3251

**Comment by dirtycoder** [comment]
Using GCE doesn't help.

**Comment by cuducos** [comment]
I don't remember by heart, but do you actually write any files into the file system?

I do that for a really small file in my test for [webassets-elm](https://github.com/cuducos/webassets-elm/blob/master/webassets_elm/tests.py) and it takes ages in Travis. It's only 1min for the whole [InternetSemLimites API](https://github.com/InternetSemLimites/PublicAPI) test suit, but 5min for the single test from webassets-elm…

**Comment by dirtycoder** [comment]
@cuducos if I remember correctly there's a few writes, in a few POST tests, the image will be written down to the disk.

By reading the related bug in travis, looks like the problem could be with phantomjs, there's a comment about moving to Firefox solve the problem, but I'd like to make this the least resource.

I have just forwarded an email to you.

**Comment by cuducos** [comment]
Ok, I'm not sure I'll use the debug mentioned in the debug because I don't have the API token. However with `-v 3` I'll know which test exactly is causing the timeout and inspect it. Gonna follow up these PR, please don't merge it yet, ok?

**Comment by dirtycoder** [comment]
@cuducos if I remember correctly, from the last time I looked at it, the test that freeze will be kind of random. I may be wrong, so just ignore it. haha
Ok! What do you think about adding a some kind of tag in the title? [WIP] or something like that, to be easier to identify that's a work in progress.

**Comment by cuducos** [comment]
About the tag: it's really up to you. In my opinion an open PR with
discussion going on is always a WIP. But how one maintain one's own repo is
not my business; and in case of Pets I'll still around either way ; )

**Comment by dirtycoder** [comment]
Yeah, I don't think such label makes much sense in a small project. :stuck_out_tongue: 
Let's leave this out for now.

**Comment by dirtycoder** [comment]
After facing this error again, using a recent version of phantomjs seems to have solved this problem, at least for now.
