### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by agreements** [dirtycoder/pets#3]
i would love to see this in action. Any demo?

**Comment by dirtycoder** [comment]
Hi @agreements, I'm glad to know someone is interested in the project. :smile:

There's a live version, in fact there's a few users already, you can check it at:
http://www.cademeubicho.com/

Unfortunately it's available only in pt-br, I'm planning to internationalize the most part of the UI soon.

The live version is exactly the same as this one is the next branch.
