### ISSUE TITLE
Automatically send email to users after some time 

### ISSUE THREAD

**Issue by dirtycoder** [dirtycoder/pets#7]
Create a management command to send email to users after a given amount of months requesting information about the status of their pet.

Something like this, but much more polite:
Was it found/adopted? Please update the status within the app.

**Comment by paulo-romano** [comment]
@dirtycoder can I do this?

**Comment by dirtycoder** [comment]
@paulo-romano sure! :)

I'd like it to be a management command, like [this](https://github.com/dirtycoder/pets/blob/next/pets/meupet/management/commands/shareonfacebook.py).

What I was thinking about was:
The command would check the _modified_ date and if it is more than 3 months ago then send an email to the user and update.
Only pets with status MISSING or FOR_ADOPTION should be checked.

If you would like to make me extra happy :smile: there's other two points here:

1. It's probably a good idea to make it available through the Admin interface as a custom action.
2. Unit tests! :heart:

**Comment by paulo-romano** [comment]
Copy that. 
I agree with the first point , I had already thought of it.
The second is always required. XD rsrs

Please, assign this issue to me. ;)

**Comment by dirtycoder** [comment]
@paulo-romano haha great! :)

Because the way GitHub deals with it I can't assign it to you, but to make clear it's being worked by someone I'll assign it to me, ok?

**Comment by paulo-romano** [comment]
Ok.
